//This is CodeGenerated by program
public class AbstractFactory {

Node car(){
nullreturn new Node(1);}

void car2(int num){
nullnum = 0+1;return num +2;}

//class:Mediator Pattern
public void main(String[] args){

return car1(3);
}
}